In [1]:
import pandas as pd

In [2]:
alunos = [
    {"nome": "Brastemp", "curso": "biomol", "origem": "sao carlos"},
    {"nome": "Fapesp", "curso": "biomol", "origem": "passos"},
    {"nome": "Gildo", "curso": "fiscomp", "origem": "fortaleza"},
    {"nome": "Sofia", "curso": "fisica", "origem": "resende"},
]

In [3]:
alunos_df = pd.DataFrame(alunos)

In [4]:
alunos_df

       nome    curso      origem
0  Brastemp   biomol  sao carlos
1    Fapesp   biomol      passos
2     Gildo  fiscomp   fortaleza
3     Sofia   fisica     resende

In [5]:
alunos_df[alunos_df["curso"]=="biomol"]

       nome   curso      origem
0  Brastemp  biomol  sao carlos
1    Fapesp  biomol      passos